alter table PIZZA_ORDER add constraint FK_PIZZA_ORDER_ON_INFORMATION foreign key (INFORMATION_ID) references PIZZA_ORDER_INFORMATION(ID);
alter table PIZZA_ORDER add constraint FK_PIZZA_ORDER_ON_POSITIONS foreign key (POSITIONS_ID) references PIZZA_ORDER_POSITION(ID);
create unique index IDX_PIZZA_ORDER_UK_NUMBER_ on PIZZA_ORDER (NUMBER_) where DELETE_TS is null ;
create index IDX_PIZZA_ORDER_ON_INFORMATION on PIZZA_ORDER (INFORMATION_ID);
create index IDX_PIZZA_ORDER_ON_POSITIONS on PIZZA_ORDER (POSITIONS_ID);
