alter table PIZZA_ORDER_INFORMATION add constraint FK_PIZZA_ORDER_INFORMATION_ON_COURIER foreign key (COURIER_ID) references SEC_USER(ID);
create index IDX_PIZZA_ORDER_INFORMATION_ON_COURIER on PIZZA_ORDER_INFORMATION (COURIER_ID);
