alter table PIZZA_INGREDIENT add constraint FK_PIZZA_INGREDIENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID);
alter table PIZZA_INGREDIENT add constraint FK_PIZZA_INGREDIENT_ON_TOPPING foreign key (TOPPING_ID) references PIZZA_TOPPING(ID);
create index IDX_PIZZA_INGREDIENT_ON_PIZZA on PIZZA_INGREDIENT (PIZZA_ID);
create index IDX_PIZZA_INGREDIENT_ON_TOPPING on PIZZA_INGREDIENT (TOPPING_ID);
